# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
