# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nlb_proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpProxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_domain_name', models.CharField(default='', max_length=128, unique=True, verbose_name='代理域名')),
                ('app_name', models.CharField(default='', max_length=128, unique=True, verbose_name='代理应用')),
                ('app_port', models.IntegerField(default=0, verbose_name='应用端口')),
                ('app_servers', models.TextField(default='', verbose_name='应用服务器')),
                ('app_servers_backup', models.TextField(default='', verbose_name='热备服务器')),
                ('other_domain_names', models.TextField(default='', verbose_name='其他代理域名')),
                ('proxy_listen_ports', models.TextField(default='', verbose_name='监听端口')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('is_disabled', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否停用')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_httpproxies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TcpProxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=128, unique=True, verbose_name='应用名称')),
                ('app_port', models.IntegerField(default=0, verbose_name='应用端口')),
                ('proxy_port', models.IntegerField(default=0, unique=True, verbose_name='代理端口')),
                ('app_servers', models.TextField(default='', verbose_name='后端服务器')),
                ('app_servers_backup', models.TextField(default='', verbose_name='热备服务器')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('is_disabled', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否停用')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tcpproxies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
