# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0003_httpproxy_push_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=128, unique=True, verbose_name='主机名')),
                ('ip', models.CharField(default='', max_length=128, unique=True, verbose_name='IP地址')),
                ('role', models.CharField(choices=[('MASTER', '主节点'), ('MINION', '从节点')], default='MINION', max_length=16, verbose_name='集群角色')),
                ('is_init', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否初始化')),
                ('is_up', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否存活')),
            ],
        ),
    ]
