# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0005_auto_20180402_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLBConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('initConfig', '初始化配置')], default='', max_length=16, unique=True, verbose_name='配置项目')),
                ('content', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
