# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0009_auto_20180423_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('http', '七层代理'), ('tcp', '四层代理'), ('whitelist', '白名单')], default='', max_length=16, verbose_name='应用类型')),
                ('target_id', models.IntegerField(default=0, verbose_name='应用ID')),
                ('log_path', jsonfield.fields.JSONField(default={}, verbose_name='日志路径')),
                ('message', models.TextField(default='', verbose_name='错误消息')),
            ],
        ),
        migrations.AlterField(
            model_name='httpproxy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '下发成功'), (2, '下发失败')], default=0, verbose_name='推送状态'),
        ),
        migrations.AlterField(
            model_name='tcpproxy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '下发成功'), (2, '下发失败')], default=0, verbose_name='推送状态'),
        ),
    ]
