# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nlb_proxy', '0012_tcpproxy_proxy_domain_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpWhiteListIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=32, unique=True, verbose_name='IP地址')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_httpwhitelistips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteListStrategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(default='', max_length=128, unique=True, verbose_name='策略名称')),
                ('http_proxy_id', models.IntegerField(default=-1, unique=True, verbose_name='所属七层代理')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('is_disabled', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否停用')),
                ('push_stat', models.IntegerField(choices=[(0, '等待下发'), (1, '下发成功'), (2, '下发失败')], default=0, verbose_name='推送状态')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_httpwhitelists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='clustermember',
            name='ip',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='pushlog',
            name='target_id',
            field=models.IntegerField(default=-1, verbose_name='应用ID'),
        ),
        migrations.AddField(
            model_name='httpwhitelistip',
            name='instance_belong',
            field=models.ManyToManyField(to='nlb_proxy.WhiteListStrategy'),
        ),
    ]
