# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-10 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nlb_proxy', '0013_auto_20180509_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlIPList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=32, unique=True, verbose_name='IP地址')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_httpwhitelistips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='httpwhitelistip',
            name='add_user',
        ),
        migrations.RemoveField(
            model_name='httpwhitelistip',
            name='instance_belong',
        ),
        migrations.RemoveField(
            model_name='whiteliststrategy',
            name='http_proxy_id',
        ),
        migrations.AddField(
            model_name='whiteliststrategy',
            name='proxy_id',
            field=models.IntegerField(default=-1, verbose_name='所属应用代理'),
        ),
        migrations.AddField(
            model_name='whiteliststrategy',
            name='proxy_type',
            field=models.CharField(choices=[('http', '七层代理'), ('tcp', '四层代理')], default='http', max_length=8, verbose_name='所属代理类型'),
        ),
        migrations.DeleteModel(
            name='HttpWhiteListIP',
        ),
        migrations.AddField(
            model_name='whiteliststrategy',
            name='access_ip',
            field=models.ManyToManyField(related_name='whitelist_refers', to='nlb_proxy.AccessControlIPList'),
        ),
    ]
