# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0014_auto_20180510_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiteliststrategy',
            name='proxy_id',
        ),
        migrations.RemoveField(
            model_name='whiteliststrategy',
            name='proxy_type',
        ),
        migrations.AddField(
            model_name='whiteliststrategy',
            name='proxy_domain_name',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='所属应用代理'),
        ),
    ]
