# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0015_auto_20180511_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpproxy',
            name='apply_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '下发成功'), (2, '下发失败')], default=0, verbose_name='下发状态'),
        ),
        migrations.AlterField(
            model_name='httpproxy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送多的应用')], default=0, verbose_name='推送状态'),
        ),
        migrations.AlterField(
            model_name='tcpproxy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送多的应用')], default=0, verbose_name='推送状态'),
        ),
        migrations.AlterField(
            model_name='whiteliststrategy',
            name='add_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelist_refers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whiteliststrategy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送多的应用')], default=0, verbose_name='推送状态'),
        ),
    ]
