# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0016_auto_20180514_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcpproxy',
            name='apply_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '下发成功'), (2, '下发失败')], default=0, verbose_name='下发状态'),
        ),
        migrations.AddField(
            model_name='whiteliststrategy',
            name='apply_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '下发成功'), (2, '下发失败')], default=0, verbose_name='下发状态'),
        ),
    ]
