# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nlb_proxy', '0017_auto_20180514_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListStrategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(default='', max_length=128, unique=True, verbose_name='策略名称')),
                ('proxy_domain_name', models.CharField(default='', max_length=128, unique=True, verbose_name='所属应用代理')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('is_deleted', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('is_disabled', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否停用')),
                ('push_stat', models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送多的应用')], default=0, verbose_name='推送状态')),
                ('apply_stat', models.IntegerField(choices=[(0, '等待下发'), (1, '下发成功'), (2, '下发失败')], default=0, verbose_name='下发状态')),
                ('access_ip', models.ManyToManyField(related_name='blacklist_refers', to='nlb_proxy.AccessControlIPList')),
                ('add_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_refers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
