# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0018_blackliststrategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blackliststrategy',
            old_name='access_ip',
            new_name='iplist',
        ),
        migrations.RenameField(
            model_name='whiteliststrategy',
            old_name='access_ip',
            new_name='iplist',
        ),
    ]
