# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0020_auto_20180516_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blackliststrategy',
            old_name='proxy_domain_name',
            new_name='proxy_belong',
        ),
        migrations.RenameField(
            model_name='whiteliststrategy',
            old_name='proxy_domain_name',
            new_name='proxy_belong',
        ),
    ]
