# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0021_auto_20180516_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermember',
            name='need_reload',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否需要reload'),
        ),
        migrations.AlterField(
            model_name='blackliststrategy',
            name='apply_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '已生效'), (2, '下发失败'), (3, '下发成功，等待reload')], default=0, verbose_name='下发状态'),
        ),
        migrations.AlterField(
            model_name='blackliststrategy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送过的应用')], default=0, verbose_name='推送状态'),
        ),
        migrations.AlterField(
            model_name='clustermember',
            name='is_alive',
            field=models.IntegerField(choices=[(0, '等待被master接受'), (1, '状态正常'), (2, 'salt-minion状态异常'), (3, 'nginx状态异常'), (4, 'Master is down!')], default=0, verbose_name='是否存活'),
        ),
        migrations.AlterField(
            model_name='httpproxy',
            name='apply_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '已生效'), (2, '下发失败'), (3, '下发成功，等待reload')], default=0, verbose_name='下发状态'),
        ),
        migrations.AlterField(
            model_name='httpproxy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送过的应用')], default=0, verbose_name='推送状态'),
        ),
        migrations.AlterField(
            model_name='tcpproxy',
            name='apply_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '已生效'), (2, '下发失败'), (3, '下发成功，等待reload')], default=0, verbose_name='下发状态'),
        ),
        migrations.AlterField(
            model_name='tcpproxy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送过的应用')], default=0, verbose_name='推送状态'),
        ),
        migrations.AlterField(
            model_name='whiteliststrategy',
            name='apply_stat',
            field=models.IntegerField(choices=[(0, '等待下发'), (1, '已生效'), (2, '下发失败'), (3, '下发成功，等待reload')], default=0, verbose_name='下发状态'),
        ),
        migrations.AlterField(
            model_name='whiteliststrategy',
            name='push_stat',
            field=models.IntegerField(choices=[(0, '新应用，未曾推送过'), (1, '已成功推送过的应用')], default=0, verbose_name='推送状态'),
        ),
    ]
