# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlb_proxy', '0022_auto_20180525_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermember',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除'),
        ),
    ]
