# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geniusalt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=8, unique=True, verbose_name='用户名称')),
                ('token', models.CharField(default='', max_length=64, unique=True, verbose_name='用户TOKEN')),
                ('sign_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('expired_time', models.IntegerField(default=86400, verbose_name='有效期限')),
            ],
        ),
        migrations.CreateModel(
            name='IncludeRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True, verbose_name='子模块名称')),
                ('is_lock', models.IntegerField(choices=[(0, '否'), (1, '是')], default='0', verbose_name='是否锁定')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True, verbose_name='模块名称')),
                ('pillar_required', jsonfield.fields.JSONField(default=[])),
                ('pillar_optional', jsonfield.fields.JSONField(default=[])),
                ('lock_count', models.IntegerField(default='0', verbose_name='锁定计数')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True, verbose_name='节点名称')),
                ('environment', models.CharField(default='', max_length=128, verbose_name='所属环境')),
                ('is_lock', models.IntegerField(choices=[(0, '否'), (1, '是')], default='0', verbose_name='是否锁定')),
                ('bind_instances', models.ManyToManyField(to='geniusalt.Instance')),
                ('bind_modules', models.ManyToManyField(to='geniusalt.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar_name', models.CharField(default='', max_length=128, verbose_name='pillar名称')),
                ('pillar_value', models.TextField(default='', verbose_name='pillar值')),
                ('environment', models.CharField(default='', max_length=128, verbose_name='环境标签')),
                ('instance_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='geniusalt.Instance')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='module_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='geniusalt.Module'),
        ),
        migrations.AddField(
            model_name='includerelationship',
            name='r_included',
            field=models.ManyToManyField(to='geniusalt.Instance'),
        ),
        migrations.AddField(
            model_name='includerelationship',
            name='r_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r_instance', to='geniusalt.Instance'),
        ),
    ]
